travis:
  secure:
    BINSTAR_TOKEN: EdD8OcXMdHGmSsG7voIIMte3ZQbK3ffTDG8mPD157blCAtAkm/zVcrMhRdx6PjGB8MdmQf0G3Lld8QAcZxASIGSWT3R2wkdYlY+VmEDdaLx8aZiUTpWok1IrbtuQScOLP3hP9188nklN/zxhTRMXEITcoh+qqke3KDDKwLi8Yj7+G6WBXc07Q6pBIG9sgTRMXE4ul0rEok0n4X/8JJ9kWT2yAgOisEVj8z2+Ie/4czY5XtbizJx4zGP6dkunNim1p3RGd7xyQyPGZqNDjIGNR9xcdDbiPQSiyVCJtwRChnngSUGj2R46UlpYtci6e3p/5EyCSlxt7mid5X0odaPZlZzv6sTlJZ2mldv7L8WCteQjm+wJy9ml82QonLdZmq/R+0nD1wjVh+ozpnAU/EJvW2aR4TPJ/bvvL/7fgFoWeRhBBGHhK2iJUnWimaHRJAXZvn0MTAvGp0/R9L8z1hl5Yto8GD3q5tsjEVuyw8XRu5XuQhK2THtQx2yRsoCqTcOJUy/CNL6phBaU0wVi4zOOUg3QpxEm90X5G6JLYm8rpc69+obys88m55mG64rmfEkPNLQvfebcUmerNL0VmJGyjd5Ce0NZeTgicKKwpTCFtIWLXyO0k0M4rZokCKbeHBSQcJINeiMYiP5fq+u59aoUIs+uvYhhgsLveaEgZeZwrbk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
