appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: M65KWVB92M02Izv1wZDJTA3o+sUGppMx69GiLyd/X5LX3rO/wWcMKdIuW4t3IVGleHlgBec6CAf1VldLegpwaZnW6lCC2RHSdNT95iu6HEdIWcb31oKFuiX3KsLb1cAZ9SwI0H6Si/1uQie5ynauN4aENs9CDEYtsHnDf4lZ7bWskgbTu7RZucXeCHTgjzTjX35uGbmFnQJnOwuP2L9XgGNbgVs36JlDWpTG4XIe10MwLQrcp9W6WL2+BIzASGvgLpamSyPTd+z+fM1M2MvuaMtw9BHNL3eyueF+4ITH+uNTrdwz5OMcjj/M9+ffi1+opIvomS1ZIF7buIKwvHwm90SRSL48qteE1EeKCu9BKGDMTGlr/H2zfze3EHemYCHUvBDwQNTIRRauQaS3GJloPp8WnJZ6WoE/5Zdy6HZcjdGh0Md1iDTuaEskGg2YQZj8+6KqYZ5JSC6CBGF4OibXR6iyNLcp5SiJrVeFZiPnkX2jJK0DN4aiMN5/RaXxfNUicDI3/d/U0UHhNuCzIo0cfBXF99nhZazLSx9X5X+NigczvxSvg1CHraPJeJ/mKiyTRe54e2kw5xiK6lAeQXM3yK+gPFG7yHVSYAWG7U9MikLcgHgwMJYjqAqnw+ALanmGRfK5DocP2JqhOwNgFZ7YNWQYL8KePiEQx87ydB84+P8=}
bot:
  automerge: true
